<a href="https://colab.research.google.com/github/kszysix/lm-learn/blob/main/supervised/basics/linreg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
# import gym
# # !pip install gym-chess
# import gym_chess

In [14]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(x)

In [15]:
x = x.reshape((m,1))
o = np.ones((m,1))
x = np.append(o,x,axis=1)

In [16]:
np.dot(x.T, x)

array([[ 6., 21.],
       [21., 91.]])

In [17]:
xl = np.linalg.inv(np.dot(x.T,x))
yp = np.dot(x.T, y)
np.dot(xl, yp)

array([2750.,  250.])

In [20]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(x,y)

reg.intercept_
reg.coef_

array([  0., 250.])